.TH SRPROF 1 "24 February 1993" "University of Arizona"
.SH NAME
srprof \- SR profiler
.SH SYNOPSIS
\fBsrprof [ \-a ] [ \fRtracefile\fP ]
.SH DESCRIPTION
.LP
.I Srprof
reads a trace file produced by an SR program
and totals the counts of the events by line number.
If the
.B \-a
option is given, the report is produced in the form of an
annotated program listing.
.SH "SEE ALSO"
.LP
sr(1), srtrace(5)
.SH CAVEATS
.LP
An annotated listing can be produced only when
.I srprof
is run in the directory containing the source files.
