##	Makefile for the SR preprocessors:  ccr2sr m2sr csp2sr



SHELL = /bin/sh



all:	ccr2sr m2sr csp2sr

ccr2sr:	    ccr2sr.head ../paths.sh common.sh ccr2sr.tail
	cat ccr2sr.head ../paths.sh common.sh ccr2sr.tail	>ccr2sr
	chmod +x ccr2sr

m2sr:	    m2sr.head ../paths.sh common.sh m2sr.tail
	cat m2sr.head ../paths.sh common.sh m2sr.tail		>m2sr
	chmod +x m2sr

csp2sr:	    csp2sr.head ../paths.sh common.sh csp2sr.tail
	cat csp2sr.head ../paths.sh common.sh csp2sr.tail	>csp2sr
	chmod +x csp2sr


clean:

depend:

lint:

tags:

TAGS:
